### ISSUE TITLE
Feature request: Make export fields selectable

### ISSUE THREAD

**Issue by casperklein** [markjszy/SimpleSelectionExport#3]
Thank you for that plugin, that was exactly what I needed today :-)

In my case, I only needed to export username/password. It would be nice, if you could choose which fields to export.

**Comment by markjszy** [comment]
Thanks for the feedback @casperklein! I just saw this recommendation and will think about it. I don't want to add too many steps to the export flow, but think that a field selector would make sense as an interstitial after file selection, along with other options (e.g. delimiter for CSV).
